import = ["~/.config/alacritty/nord.toml"]
live_config_reload = true

[shell]
program = "/usr/bin/fish"

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.90

[window.padding]
x = 5
y = 5

[font]
size = 16

[font.bold]
family = "FantasqueSansM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FantasqueSansM Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FantasqueSansM Nerd Font"
style = "Italic"

[font.normal]
family = "FantasqueSansM Nerd Font"
style = "Regular"

[[keyboard.bindings]]
key = "Return"
mods = "Alt|Shift"
action = "SpawnNewInstance"
