# Colors (Evergarden Hard)

# Default colors
[colors.primary]
background = '#1A2024'
foreground = '#D3C6AA'

# Normal colors
[colors.normal]
black   = '#343E44'
red     = '#E67E80'
green   = '#B2C98F'
yellow  = '#DBBC7F'
blue    = '#A2C8C3'
magenta = '#D699B6'
cyan    = '#88C096'
white   = '#7A8478'

# Bright colors
[colors.bright]
black   = '#343E44'
red     = '#E67E80'
green   = '#B2C98F'
yellow  = '#DBBC7F'
blue    = '#A2C8C3'
magenta = '#D699B6'
cyan    = '#88C096'
white   = '#7A8478'
