[colors.primary]
background = "#222222"
foreground = "#F7F1FF"

[colors.normal]
black = "#131313"
red = "#FC618D"
green = "#FCE566"
yellow = "#7BD88F"
blue = "#948AE3"
magenta = "#FD9353"
cyan = "#5AD4E6"
white = "#F7F1FF"
